development:
  startup_wait: 15
  url: 'http://127.0.0.1:8983/solr/blacklight-core'
  jetty_port: 8983
test:
  startup_wait: 60
  jetty_port: <%= ENV['TEST_JETTY_PORT'] || 8888 %>
  <%= ENV['TEST_JETTY_PATH'] ? "jetty_home: " + ENV['TEST_JETTY_PATH'] : '' %>
production:
  startup_wait: 15
  url: 'http://127.0.0.1:8983/solr/blacklight-core'
  jetty_port: 8983